server:
  port: 8888
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-config-server
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/sheetanchor/Micro-demo.git
          searchPaths: 'springcloud-config-profile/{application}'
          default-label: master
          #username:
          #password:
security:
  basic:
    enabled: true
  user:
    #这是config-server的用户名和密码
    name: config
    password: config